version: '3.8'

services:
  nginx:
    image: nginx:1.15
    container_name: nginx
    volumes:
      - ./:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - my-network
    depends_on:
      - controle_financeiro
    restart: always

    
  controle_financeiro:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: controle_financeiro
    volumes:
      - ./:/var/www
    command: poetry run gunicorn --bind 0.0.0.0:8000 --workers 4 "app.app:create_app()"
    depends_on:
      - db
    env_file:
      - .env
    restart: always
    networks:
      my-network:
        aliases:
          - flask-app
    

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      - POSTGRES_USER=controle_financeiro
      - POSTGRES_PASSWORD=controle_financeiro
      - POSTGRES_DB=controle_financeiro_dev
    ports:
      - 5432:5432
    expose:
      - 5432

volumes:
  postgres_data:

networks:
  my-network:
