"""empty message

Revision ID: 51c834695db1
Revises: 9a09cf5db78d
Create Date: 2022-08-15 14:07:25.425671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c834695db1'
down_revision = '9a09cf5db78d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('despesas', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_descricao_for_data', ['descricao', 'data'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('despesas', schema=None) as batch_op:
        batch_op.drop_constraint('unique_descricao_for_data', type_='unique')

    # ### end Alembic commands ###
